### PR TITLE
add configuration for snapshot testing

### LINKED ISSUE #30: Add Snapshot Testing
**Description**

The goal is to add test visual tests for all the components to ensure that the designs are not changed with change in code.
**Problems solved**

Tests make it easy to identify breaking changes and fix them as and when they occur.

**Alternatives**

**Additional context**

**Want to take up?**

Yes

### PR DESCRIPTION
**Pull request by silvinabt87**
## Fixes

Fixes #30 

## Description
This PR sets up configuration fro snapshot tests. When running ```npm run test:snapshot``` ( test:integration is not found), an error shows:
```
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-es2015-modules-commonjs' from '/home/silvina/projects/fonts'

      at Function.module.exports [as sync] (../../node_modules/resolve/lib/sync.js:72:15)
      at resolveStandardizedName (../../node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (../../node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (../../node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (../../node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (../../node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (../../node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (../../node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (../../node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
```

## Checklist
 
- [x ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x ] My pull request targets the `master` branch of the repository.
- [x ] My commit messages follow [best practices][best_practices].
- [x ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
I'm not sure what this PR is trying to solve. The infrastructure for testing has already been added so any **PRs after that should only be adding, or changing, individual test files** and test cases, not modifying helpers and configuration files.

**Comment by silvinabt87** [comment]
@dhruvkb I understand that. I did this PR because I set up the configuration as per #33 but it didn't seem to work, aside from the fact that the test itself was not correct. This PR has to do with this [comment](https://github.com/creativecommons/fonts/issues/30#issuecomment-609457316), where I'm asking for assistance. I've checked what you've shared and will proceed as per your responses

**Comment by dhruvkb** [comment]
@silvinabt87 try running the tests with Docker. See https://github.com/creativecommons/fonts/issues/30#issuecomment-609465011. Let me know on Slack if you're still stuck.

**Comment by silvinabt87** [comment]
@dhruvkb I saw your comment and I've installed Docker and Docker Compose with its documentation instructions. Everything seems to be right with the installation but when I try to run it according to Vocabulary instructions, I get an error ```Can't find a suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml``` 
I sent you a message on Slack because I've tried troubleshooting in several ways but I can't seem to find a solution.

**Comment by dhruvkb** [comment]
Issue #30 has been resolved by PR #50.

**Pull request closed without merging**
