### PR TITLE
Added manual setup instructions

### LINKED ISSUE #21: Update instructions.md
**Description**

This issue aims at updating instructions.md file
**Reproduction**

**Expected behavior**

**Screenshots**

**Conditions:**

**Additional context**

**Want to take up?**

[Yes|No]
Yes

### PR DESCRIPTION
**Pull request by megha070**
**Fixes**

Fixes #21 by @megha070

**Description**
Updated instructions.md

**Type of PR** 
This PR is a hotfix.

**Technicalities**

**Tests**

**Screenshots**

**Checklist:**
 
- [ x] My pull request has a descriptive title (not a vague title like "Update `index.md`").
- [ x] My pull request targets the `master` branch of the repository.
- [x ] My commit messages follow [best practices][best_practices].
- [ x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Legal**
By submitting this PR, I agree to abide by the terms of the Developer 
Certificate of Origin.

<details>
<summary>Developer Certificate of Origin</summary>

Developer Certificate of Origin<br>
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.<br>
1 Letterman Drive<br>
Suite D4700<br>
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
</details>

### CODE REVIEW

**Comment by megha070** [comment]
@dhruvkb Please review this and let me know if this is relevant.

**Review by dhruvkb — COMMENTED** [review]
@megha070 this is good. I'll take a closer look later on.

**Comment by jahnvigupta** [comment]
@megha070 I was trying to run npm run storybook in fonts directory and it gave me the error 
sh: 1: webpack: not found
and I resolved it by running 
yarn add webpack webpack-dev-server --dev
I think it would be good if you add this command in your documentation to help future contributors.

**Comment by jahnvigupta** [comment]
I think this command
yarn add webpack webpack-dev-server --dev
should be added as I was getting error before running this.

**Comment by megha070** [comment]
Hey, @jahnvigupta I guess we should use npm for CC projects so as to maintain uniformity across all CC projects. Apart from this Yarn is Facebook's package manager which sends package usage information to Facebook and it doesn't have lock file support. Please correct me if I am wrong. If we can use Yarn as well, I will add steps for yarn too. 
@dhruvkb

**Comment by jahnvigupta** [comment]
You can add this command then,
npm install webpack webpack-dev-server --save-dev

**Comment by dhruvkb** [comment]
We don't use Yarn because `npm` is well-known, quite popular, very official and now will have even more support with GitHub thanks to the acquisition. Yarn on the other hand seems to have taken a different direction since Yarn 2 and we can't deal with that sort of breaking change as we're a small team that's already stretched pretty thin.

**Comment by dhruvkb** [comment]
@jahnvigupta I've never actually needed to install any dev server to make the repo work so if you could open a new issue to discuss that, it would be pretty awesome. Meanwhile I'm going to close this PR as this work will be superseded by work on #34.

**Pull request closed without merging**
