### PR TITLE
Unit test for icons components

### LINKED ISSUE #36: Write Unit Tests for components in fonts
**Description**
The goal is to add unit testing to the repository for all the components

**Problems solved**
Tests make it easy to identify breaking changes and fix them as and when they occur.

**Alternatives**

**Additional context**

**Want to take up?**

[Yes|No]
Yes

### PR DESCRIPTION
**Pull request by kushaggarwal**
## Fixes

Fixes #36 by @megha070 

## Description

This PR aims at the addition of general template of unit testing with jest
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
The infrastructure for the tests has already been added so just write the unit tests without the supporting files.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb please find the above changes associated with the current infrastructure of the unit test

**Review by dhruvkb — CHANGES_REQUESTED** [review]
Why have `package.json` and `package-lock.json` been modified?

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
While merging fonts from creative commons for the infrastructure in order to specify and run the tests I was having an error while pulling the changes therefore had to manually update both the files to resolve the conflict

**Comment by dhruvkb** [comment]
@kushaggarwal in that case you should completely go with the file in `master` branch. Anyways, try using two spaces instead of four in indentation and maybe the conflict will not appear at all.

**Comment by kushaggarwal** [comment]
Okay @dhruvkb 
Will update the following 
Thank you

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
