### PR TITLE
Updated docs to inlcude more info on VocabularyIcons.json file

### LINKED ISSUE #90: Increase the prominence of VocabularyIcons.json in the documentation
## Problem
The current `Contribution` documentation doesn't focus much light on how you should you go on updating the `VocabularyIcons.json` file after downloading the Icomoon zip folder and updating the relevant stories and .woff and .ttf files.  

## Description
The responsible section under the documentation should elaborate on the updating part of `VocabularyIcons.json` file.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by Dishebh**
## Fixes

Fixes #90  by @Dishebh 

## Description
Updated docs to inlcude more info on VocabularyIcons.json file and how to update it.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
You can directly grab the updated JSON file here:
2020-06-10 09 25 54 icomoon io d0223b73a3ab

**Comment by Dishebh** [comment]
@dhruvkb, wouldn't it be better if we shift this

> At the end of the process, come back to this Projects page, use the Download option to get the JSON data dump of the project and add it to the directory src/fonts/ as well.

from the middle to the end of the section, as it will behave in a manner of maintaining procedural integrity? Moreover, it kind of seems unclear as to which process is it referring to in `At the end of the process ...`.

**Comment by dhruvkb** [comment]
Yes, @Dishebh please move this to the end. You're right about it breaking the flow of the page and giving instructions about the end that people will forget by the time they reach the end.

**Review by dhruvkb — CHANGES_REQUESTED** [review]
This PR contains a lot of changes that do not relate to the agenda of the PR. Please confine the changes to those directly addressing the issue and file a different issue and PR for the other changes.

**Comment by Dishebh** [comment]
@dhruvkb prettier is the culprit here. If you say, can I add the prettier config here as well, first, so as to avoid this issue?

**Comment by dhruvkb** [comment]
@Dishebh we've not settled on Prettier yet so please turn it off and update this PR for now.

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
